name: Oura Profile Cards

on:
  schedule:
    - cron: '0 0 * * *' # Run every 24 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: savvan0h/oura-profile-cards@main
        env:
          OURA_API_TOKEN: ${{ secrets.OURA_API_TOKEN }}
