name: Oura Profile Cards

on:
  schedule:
    - cron: '0 */3 * * *' # Run every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: savvan0h/oura-profile-cards@v0.1.0
        with:
          OURA_API_TOKEN: ${{ secrets.OURA_API_TOKEN }}
